version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
    command: ./fresh -c fresh.conf
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
